language: python
python:
  - "3.4"
# command to install dependencies
install:
  - "pip install -r requirements.txt"


# command to run tests
script:
   - pytest --with-coverage --cover-tests
   - coverage report


after_success:
  - coveralls